FROM tiangolo/uvicorn-gunicorn:python3.10
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install --no-cache-dir fastapi
RUN pip install -r requirements.txt
COPY ./app /app
CMD [ "python", "trtest.py"]
